FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY gradlew .
COPY gradle/wrapper ./gradle/wrapper
COPY build.gradle.kts .
COPY settings.gradle.kts .

COPY src ./src

RUN chmod +x gradlew && ./gradlew clean build

COPY build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "app.jar" ]